name: Build and Run Docker Container

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    timeout-minutes: 3600

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file from secrets
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env

    - name: Build Docker image
      run: docker build -t verfication-bot .

    - name: Run Docker container
      run: |
        chmod +x deploy.sh
        ./deploy.sh
